services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    group_add:
      - 44
    network_mode: "host"
    volumes:
      - /home/admink/jellyfin/config:/config
      - /home/admink/jellyfin/cache:/cache
      - /vault/mediavault/Films:/media/films:ro
      - /vault/mediavault/FilmsFR:/media/films-fr:ro
      - /vault/mediavault/Series:/media/series:ro
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://89.89.160.182:8096
    devices:
      - /dev/dri:/dev/dri